export { BeardLight } from './BeardLight'
export { BeardMajestic } from './BeardMajestic'
export { BeardMedium } from './BeardMedium'
export { Blank } from './Blank'
export { MoustacheFancy } from './MoustacheFancy'
export { MoustacheMagnum } from './MoustacheMagnum'
